FROM amazoncorretto:17.0.11-alpine3.19

COPY ./src/main /app/renaissance/src/main
COPY ./pom.xml /app/renaissance/pom.xml

RUN apk add --no-cache maven

ARG APPLICATION_USER=urenaissance
RUN adduser -u 1000 -D $APPLICATION_USER
RUN chown -R $APPLICATION_USER /app/

USER $APPLICATION_USER

WORKDIR /app/renaissance/
RUN mvn clean package -DskipTests

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "target/Backend-0.0.1-SNAPSHOT.jar"]