FROM amazoncorretto:17.0.11-alpine3.19

ARG APP_HOME=app

ARG BACKEND_DIR=renaissance
COPY ./src/main /${APP_HOME}/${BACKEND_DIR}/src/main
COPY ./pom.xml /${APP_HOME}/${BACKEND_DIR}/pom.xml

RUN apk add --no-cache maven

ARG APPLICATION_USER=urenaissance
RUN adduser -u 1000 -D ${APPLICATION_USER}
RUN chown -R ${APPLICATION_USER} /${APP_HOME}/

USER ${APPLICATION_USER}

WORKDIR /${APP_HOME}/${BACKEND_DIR}/
RUN mvn clean package -DskipTests -Dexec.skip=true

# Clean up
USER root
RUN apk del maven
USER ${APPLICATION_USER}

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "target/Backend-0.0.1-SNAPSHOT.jar"]