FROM alpine:3.20

RUN apk add --no-cache curl

RUN curl -sSL https://github.com/grafana/k6/releases/download/v0.41.0/k6-v0.41.0-linux-amd64.tar.gz | tar -xz -C /usr/bin

RUN PATH=/usr/bin/k6-v0.41.0-linux-amd64:$PATH

COPY ./scripts-for-tests/*.js /scripts

ENTRYPOINT ["tail", "-f", "/dev/null"]